
spring:
  application:
    name: yan-springcloud-hello

server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
