
spring:
  application:
    name: yan-springcloud-zuul

server:
  port: 8888

#zuul:
#  routes:
#    api-a:
#      path: /producer/**
#      serviceId: spring-cloud-producer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
